# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
 use_frameworks!

target 'Audition' do

pod 'PureLayout'
pod 'Alamofire'

pod 'SwiftyBeaver',
  :git => 'https://github.com/SwiftyBeaver/SwiftyBeaver',
  :branch => 'swift3'
end

