# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
 use_frameworks!

target 'Audition' do

pod 'PureLayout', '~> 3.0.2'
pod 'Alamofire', '~>3.4.2'
pod 'SwiftyBeaver', '~>0.6.5'

end

